import { redactPII } from '../utils/antonyAiRedactionUtils.js';

interface PromptGuardResult {
  isSafe: boolean;
  refusalEnglish?: string;
  refusalTelugu?: string;
  reason?: string;
}

const SUSPICIOUS_PATTERNS = [
  /ignore\s+all\s+previous/i,
  /ignore\s+above\s+instructions/i,
  /ignore\s+system\s+instructions/i,
  /you\s+are\s+now\s+a\s+different/i,
  /bypass\s+safety/i,
  /reveal\s+your\s+prompt/i,
  /show\s+your\s+system\s+instruction/i,
  /print\s+your\s+instructions/i,
  /what\s+is\s+your\s+prompt/i,
  /system\s+prompt/i,
  /override\s+instruction/i,
];

// Block clinical, diagnostic, and prescription requests
const MEDICAL_DIAGNOSIS_KEYWORDS = [
  "disease", "diagnose", "treatment for", "prescription", "cure for", "medicine list",
  "clinical advice", "medical advice", "what medicine", "inject", "tablet for", "syrup for",
  "వ్యాధి", "చికిత్స", "మందులు", "ప్రిస్క్రిప్షన్", "రోగ నిర్ధారణ"
];

/**
 * Scan inputs for prompt injection, hijack attempts, and forbidden topics (such as clinical medical requests).
 */
export function scanQuery(query: string): PromptGuardResult {
  if (!query) return { isSafe: true };

  // 1. Check for suspicious jailbreak/hijack patterns
  for (const pattern of SUSPICIOUS_PATTERNS) {
    if (pattern.test(query)) {
      return {
        isSafe: false,
        reason: "Prompt Hijack / Prompt Injection Attempt",
        refusalEnglish: "⚠️ Security Warning: System instructions override detected. This query violates school safety policies and will not be processed.",
        refusalTelugu: "⚠️ భద్రతా హెచ్చరిక: సిస్టమ్ సూచనల అధిగమనం కనుగొనబడింది. ఈ ప్రశ్న పాఠశాల భద్రతా విధానాలను ఉల్లంఘిస్తుంది మరియు ప్రాసెస్ చేయబడదు."
      };
    }
  }

  // 2. Check for medical advice requests (clinical diagnosis / prescription medicines)
  const lowerQuery = query.toLowerCase();
  const containsMedicalKeyword = MEDICAL_DIAGNOSIS_KEYWORDS.some(kw => lowerQuery.includes(kw));
  
  // Guard specifically looking for questions like "diagnose", "prescribe", "what medicine"
  const isAskingPrescription = /\b(prescribe|diagnosis|diagnose|tablet|capsule|mg|dosage|dose|paracetamol|antibiotic|ibuprofen)\b/gi.test(lowerQuery);
  
  if (containsMedicalKeyword || isAskingPrescription) {
    return {
      isSafe: false,
      reason: "Clinical / Medical prescription requested",
      refusalEnglish: "We cannot provide medical diagnosis, clinical treatment plans, or prescription recommendations. Please contact our physical healthcare center or school nurse for verified professional care.",
      refusalTelugu: "మేము వైద్య నిర్ధారణ, క్లినికల్ చికిత్స ప్రణాళికలు లేదా ప్రిస్క్రిప్షన్ సిఫార్సులను అందించలేము. దయచేసి ధృవీకరించబడిన ప్రొఫెషనల్ సంరక్షణ కోసం మా హెల్త్‌కేర్ సెంటర్ లేదా స్కూల్ నర్సును సంప్రదించండి."
    };
  }

  return { isSafe: true };
}

/**
 * Scan outputs to verify no API details, passwords, or configuration secrets generated by Gemini
 */
export function scanResponse(responseText: string): string {
  if (!responseText) return "";
  
  // 1. Scrub emails, phone numbers, and keys
  let sanitised = redactPII(responseText);

  // 2. Double checks for accidental leaks of prompt text itself
  const lowerResp = sanitised.toLowerCase();
  
  if (lowerResp.includes("system_instruction") || lowerResp.includes("smart_bot_instructions") || lowerResp.includes("smart bot instructions")) {
    sanitised = "Sorry, I had an issue formatting my response correctly. Let me know how else I can help you with school records.";
  }

  return sanitised;
}
