steps:
  # 1. Build Docker image with Google Cloud Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spears-academy-app:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/spears-academy-app:latest', '.']

  # 2. Push image to Container / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spears-academy-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spears-academy-app:latest']

  # 3. Deploy container image to Google Cloud Run with minimal cost / Free Tier settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spears-academy-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/spears-academy-app:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/spears-academy-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/spears-academy-app:latest'
